---
version: "3"
services:
  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
      - 4566:4566
      - 5691:5691
    command: playground
    container_name: risingwave
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mydb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p123456"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: mysql
  message_queue:
    image: docker.redpanda.com/vectorized/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://message_queue:29092,OUTSIDE://localhost:9092
    ports:
      - 29092:29092
      - 8081:8081
    container_name: message_queue
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9092
      interval: 1s
      timeout: 5s
      retries: 5
  debezium:
    image: debezium/connect:1.9
    environment:
      BOOTSTRAP_SERVERS: message_queue:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://message_queue:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://message_queue:8081
    volumes:
      - ./mysql:/data
    ports:
      - 8083:8083
    healthcheck:
      test: curl -f localhost:8083
      interval: 1s
      start_period: 120s
    depends_on:
      - message_queue
      - mysql
    container_name: debezium
  debezium_deploy:
    image: debezium/connect:latest
    depends_on:
      debezium:
        condition: service_healthy
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_ADDR=${EXTERNAL_IP:-redpanda}:9092
    volumes:
      - ./mysql/mysql_dbz.sh:/mysql_dbz.sh
    entrypoint: [ bash, -c, /mysql_dbz.sh ]
    container_name: debezium_deploy
    restart: on-failure
  datagen:
    image: mysql:8.0
    depends_on:
      - mysql
    command:
      - /bin/sh
      - -c
      - "mysql -p123456 -h mysql mydb < mysql_prepare.sql"
    volumes:
      - "./mysql_prepare.sql:/mysql_prepare.sql"
    container_name: datagen
    restart: on-failure
name: risingwave-compose
