---
version: "3"
services:
  spark:
    image: apache/spark:3.3.1
    command: tail -f /dev/null
    depends_on:
      - minio-0
    volumes:
      - "./spark-script:/spark-script"
    container_name: spark
  presto:
    build: ./presto-with-iceberg
    container_name: presto
  compactor-0:
    extends:
      file: ../docker/docker-compose.yml
      service: compactor-0
  compute-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: compute-node-0
  etcd-0:
    extends:
      file: ../docker/docker-compose.yml
      service: etcd-0
  frontend-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: frontend-node-0
  grafana-0:
    extends:
      file: ../docker/docker-compose.yml
      service: grafana-0
  meta-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: meta-node-0
  minio-0:
    extends:
      file: ../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../docker/docker-compose.yml
      service: prometheus-0
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mydb
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p123456" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: mysql
  connector-node:
    extends:
      file: ../docker/docker-compose.yml
      service: connector-node
  prepare_mysql:
    image: mysql:8.0
    depends_on: 
      - mysql
    command:
      - /bin/sh
      - -c
      - "mysql -p123456 -h mysql mydb < mysql_prepare.sql"
    volumes:
      - "./mysql_prepare.sql:/mysql_prepare.sql"      
    container_name: prepare_mysql
    restart: on-failure
  datagen:
    image: ghcr.io/risingwavelabs/demo-datagen:v1.1.1
    depends_on: [mysql]
    command:
      - /bin/sh
      - -c
      - /datagen --mode clickstream --qps 1 mysql --user mysqluser --password mysqlpw --host mysql --port 3306 --db mydb
    container_name: datagen
    restart: on-failure
volumes:
  compute-node-0:
    external: false
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
name: risingwave-compose