---
version: "3"
services:
  compactor-0:
    extends:
      file: ../docker/docker-compose.yml
      service: compactor-0
  compute-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: compute-node-0
  etcd-0:
    extends:
      file: ../docker/docker-compose.yml
      service: etcd-0
  frontend-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: frontend-node-0
  grafana-0:
    extends:
      file: ../docker/docker-compose.yml
      service: grafana-0
  meta-node-0:
    extends:
      file: ../docker/docker-compose.yml
      service: meta-node-0
  minio-0:
    extends:
      file: ../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../docker/docker-compose.yml
      service: prometheus-0
  message_queue:
    extends:
      file: ../docker/docker-compose.yml
      service: message_queue
  datagen:
    image: python:3.10
    depends_on: [ message_queue ]
    volumes:
      - type: bind
        source: ./datagen.py
        target: /datagen.py
    command:
      - /bin/sh
      - -c
      - |
        pip install requests fastavro confluent_kafka
        python /datagen.py message_queue:29092 http://message_queue:8081 sr-test
    restart: always
    container_name: datagen
volumes:
  compute-node-0:
    external: false
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
name: risingwave-compose
