name: Docker Build for Workload Generator

on:
  # For manually triggering workflow
  workflow_dispatch:

  push:
    tags:
      - 'v*.*.*'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./datagen
          push: true
          tags: |
            ghcr.io/risingwavelabs/demo-datagen:${{github.ref_name}}
